# Generated by Django 3.2.4 on 2021-06-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location_latitude', models.FloatField()),
                ('event_location_longitude', models.FloatField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_place', models.CharField(max_length=255)),
                ('event_image', models.ImageField(upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='about_us')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_position', models.CharField(max_length=255)),
                ('executive_description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(upload_to='news')),
                ('news_genre', models.CharField(max_length=100)),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NonExecutiveEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='about_us')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_position', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_date', models.DateField()),
                ('project_image', models.ImageField(upload_to='projects')),
                ('project_description', models.TextField()),
            ],
        ),
    ]
