# Generated by Django 3.2.4 on 2021-06-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210619_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homegallery',
            options={'verbose_name_plural': 'HomeGallery'},
        ),
        migrations.RenameField(
            model_name='homegallery',
            old_name='image_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='homegallery',
            old_name='image',
            new_name='original',
        ),
    ]
