# Generated by Django 3.2.4 on 2021-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210619_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executiveemployee',
            old_name='executive_description',
            new_name='employee_description',
        ),
        migrations.AddField(
            model_name='nonexecutiveemployee',
            name='employee_description',
            field=models.CharField(default='employee description', max_length=255),
            preserve_default=False,
        ),
    ]
