# Generated by Django 3.2.4 on 2021-06-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210625_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveemployee',
            name='employee_email',
            field=models.EmailField(default='x@x.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonexecutiveemployee',
            name='employee_email',
            field=models.EmailField(default='x@x.com', max_length=255),
            preserve_default=False,
        ),
    ]
