# Generated by Django 3.2.4 on 2021-06-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210625_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveemployee',
            name='employee_description',
        ),
        migrations.RemoveField(
            model_name='nonexecutiveemployee',
            name='employee_description',
        ),
    ]
