# Generated by Django 3.2.4 on 2021-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210625_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveemployee',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nonexecutiveemployee',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
