"""
Django settings for kiwanis project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('KIWANIS_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Similar to the SSL certificate
ALLOWED_HOSTS = [
    '.kiwanisnepali.org', 'kiwanisnepali.org',
    'backend-prod.eba-yutmxpkf.ap-south-1.elasticbeanstalk.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    'api',
    'serve',

    # 3rd party apps

    'rest_framework',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 3rd party middlewares
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'kiwanis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiwanis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('KIWANIS_DB_NAME'),
            'USER': env('KIWANIS_DB_USERNAME'),
            'PASSWORD': env('KIWANIS_DB_PASSWORD'),
            'HOST': env('KIWANIS_HOST'),
            'PORT': env('KIWANIS_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES']\
        .append('rest_framework.renderers.BrowsableAPIRenderer')

# Okay to have API requests coming from here
CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
]

# AWS bucket settings
AWS_STORAGE_BUCKET_NAME = 'elasticbeanstalk-ap-south-1-637856909234'
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_LOCATION = 'static'

# Tell django-storages the domain to use to refer to static files.

# Tell the staticfiles app to use S3Boto3 storage when writing the collected static files (when
# you run `collectstatic`).
#STATIC_URL = 'https://elasticbeanstalk-ap-south-1-637856909234.s3.ap-south-1.amazonaws.com/static/'
STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'build', 'static'),
]

MEDIAFILES_LOCATION = 'media'
STATICFILES_STORAGE = 'kiwanis.static_backends.StaticStorage'
DEFAULT_FILE_STORAGE = 'kiwanis.storage_backends.MediaStorage'

# https://elasticbeanstalk-ap-south-1-637856909234.s3.ap-south-1.amazonaws.com/static/js/main.ec150df8.chunk.js?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEDgaCXVzLWVhc3QtMiJIMEYCIQDKPNAtt%2Ba9abRg8A28Yu7LGK8DRw1WNrrBPB4vTH6XnQIhAOW2yNg0N2I8XwJm8H%2B9mjyK7rq2Qjq9hvQzbwD9mr%2BQKvYCCDEQARoMNjM3ODU2OTA5MjM0IgzqUzhH9VtqB5jTtj8q0wJahffX8SBMY4yq4x4kju1JpILMsTwsg0jQzGSbyNZB38L%2BQIyxRjkUvGHKz3ylIzwkbXFfR2nTD9L5FexnSN43lPMWwYEz93AwDZMlPFPJ5%2FWBOVNbNpn5Bt1Z6EzST%2BxozzvNvqzMO2TSdqX6iNwI3MR7CN6bibgs%2FZP%2Fw5KtSc6NrWdW1FRWwuPd2kEKi07FM88NmoANWtN0eyM7H13eHkfDFh6%2BCuAXcdABM3o8u3AJywEIFJ6Ha4qmar26QJIXZUPNaGn1pKG51F3R5ifG%2FP9j9mtsbciG8EP3JgeR%2FFSlzXVhtgM5eBASWmZyhvNMt%2FU8Ir1NrWMPPsCwtscgTAZ8Q5jswDCPrNw9CW9GN7t0vq1IlQjnlLT%2FM0MuRl56DsxUJCns34klvNqEC4rg3cZFvcRxqPyF0fPCCV1fSBcoN6mBrwfLAUqzH1w5HzOTi14wn9jAhwY6sgLoE%2B%2B%2BeatWIXOf%2F3nvsF5y0G8RZDIOIsdViSyV4BI2IQrXdFqWoDfG%2Fmjy2kEHbgP4n1LHh7CSgI0QlKntWgmnw2DivbCv0YOvoq3OALnhxeVWvi9bowKMbpInsrv%2BkGrqQa3Dw%2B3po2FpA2UtaB04swcmG6ygO1PQFMN0Ymdrda1FEW3K6ntSidf6urrYhI%2BiREZRNNx5U6ZPfsEGjOwjtK7wEwQhjdB4%2F65uN%2Fcf8AYTVpLUVi1%2FNsz0GH0t9Mlgwk%2B7cF7KZIBxhBOHRTojh2AYaeS1fBFQjd9T8wGKdz37D%2FtnrucwsnuuRjO0uc60PEpQHBDCJqc8oIzmThpIXckVBLxS4IzYPfpwL0WZxfZibvQzKlywlRdf%2BBprBD976pNks9QYBsJ2DrtVzDlNhzw%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210715T232232Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAZJAZ4A6ZI7EHI7WB%2F20210715%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Signature=73ccced6a886835a23f4624fb806be606707ac15a063db03baaf794627628b29
